### ISSUE TITLE
make a mcq test page for user

### ISSUE THREAD

**Issue by naman777** [naman777/exam-portal#2]
make a test page for user which will have two sections mcq section and coding question section for now just leave the coding question section make only the page where the mcqs are getting shown and user can select them and store the answer for each questions in local storage 

fork the repo first
make a new pr for it 

wireframe is provided 

![WhatsApp Image 2024-09-03 at 20 45 43_f309695f](https://github.com/user-attachments/assets/fa19bc24-6f38-4205-80c1-215941d9531c)

**Comment by wtfdevil666** [comment]
picking up this issue.
                        - Aryan
